USE realestate
GO
	/************************************************************************************************************************
		1.	Data discovery for creation of production table for transforming and cleaning data
	************************************************************************************************************************/

	SELECT
	MAX(LEN(PERIOD_BEGIN))PERIOD_BEGIN,
	MAX(LEN(PERIOD_END))PERIOD_END,
	MAX(LEN(PERIOD_DURATION))PERIOD_DURATION,
	MAX(LEN(REGION_TYPE))REGION_TYPE,
	MAX(LEN(REGION_TYPE_ID))REGION_TYPE_ID,
	MAX(LEN(TABLE_ID))TABLE_ID,
	MAX(LEN(IS_SEASONALLY_ADJUSTED))IS_SEASONALLY_ADJUSTED,
	MAX(LEN(REGION))REGION,
	MAX(LEN(CITY))CITY,
	MAX(LEN(STATE))STATE,
	MAX(LEN(STATE_CODE))STATE_CODE,
	MAX(LEN(PROPERTY_TYPE))PROPERTY_TYPE,
	MAX(LEN(PROPERTY_TYPE_ID))PROPERTY_TYPE_ID,
	MAX(LEN(MEDIAN_SALE_PRICE))MEDIAN_SALE_PRICE,
	MAX(LEN(MEDIAN_SALE_PRICE_MOM))MEDIAN_SALE_PRICE_MOM,
	MAX(LEN(MEDIAN_SALE_PRICE_YOY))MEDIAN_SALE_PRICE_YOY,
	MAX(LEN(MEDIAN_LIST_PRICE))MEDIAN_LIST_PRICE,
	MAX(LEN(MEDIAN_LIST_PRICE_MOM))MEDIAN_LIST_PRICE_MOM,
	MAX(LEN(MEDIAN_LIST_PRICE_YOY))MEDIAN_LIST_PRICE_YOY,
	MAX(LEN(MEDIAN_PPSF))MEDIAN_PPSF,
	MAX(LEN(MEDIAN_PPSF_MOM))MEDIAN_PPSF_MOM,
	MAX(LEN(MEDIAN_PPSF_YOY))MEDIAN_PPSF_YOY,
	MAX(LEN(MEDIAN_LIST_PPSF))MEDIAN_LIST_PPSF,
	MAX(LEN(MEDIAN_LIST_PPSF_MOM))MEDIAN_LIST_PPSF_MOM,
	MAX(LEN(MEDIAN_LIST_PPSF_YOY))MEDIAN_LIST_PPSF_YOY,
	MAX(LEN(HOMES_SOLD))HOMES_SOLD,
	MAX(LEN(HOMES_SOLD_MOM))HOMES_SOLD_MOM,
	MAX(LEN(HOMES_SOLD_YOY))HOMES_SOLD_YOY,
	MAX(LEN(PENDING_SALES))PENDING_SALES,
	MAX(LEN(PENDING_SALES_MOM))PENDING_SALES_MOM,
	MAX(LEN(PENDING_SALES_YOY))PENDING_SALES_YOY,
	MAX(LEN(NEW_LISTINGS))NEW_LISTINGS,
	MAX(LEN(NEW_LISTINGS_MOM))NEW_LISTINGS_MOM,
	MAX(LEN(NEW_LISTINGS_YOY))NEW_LISTINGS_YOY,
	MAX(LEN(INVENTORY))INVENTORY,
	MAX(LEN(INVENTORY_MOM))INVENTORY_MOM,
	MAX(LEN(INVENTORY_YOY))INVENTORY_YOY,
	MAX(LEN(MONTHS_OF_SUPPLY))MONTHS_OF_SUPPLY,
	MAX(LEN(MONTHS_OF_SUPPLY_MOM))MONTHS_OF_SUPPLY_MOM,
	MAX(LEN(MONTHS_OF_SUPPLY_YOY))MONTHS_OF_SUPPLY_YOY,
	MAX(LEN(MEDIAN_DOM))MEDIAN_DOM,
	MAX(LEN(MEDIAN_DOM_MOM))MEDIAN_DOM_MOM,
	MAX(LEN(MEDIAN_DOM_YOY))MEDIAN_DOM_YOY,
	MAX(LEN(AVG_SALE_TO_LIST))AVG_SALE_TO_LIST,
	MAX(LEN(AVG_SALE_TO_LIST_MOM))AVG_SALE_TO_LIST_MOM,
	MAX(LEN(AVG_SALE_TO_LIST_YOY))AVG_SALE_TO_LIST_YOY,
	MAX(LEN(SOLD_ABOVE_LIST))SOLD_ABOVE_LIST,
	MAX(LEN(SOLD_ABOVE_LIST_MOM))SOLD_ABOVE_LIST_MOM,
	MAX(LEN(SOLD_ABOVE_LIST_YOY))SOLD_ABOVE_LIST_YOY,
	MAX(LEN(PRICE_DROPS))PRICE_DROPS,
	MAX(LEN(PRICE_DROPS_MOM))PRICE_DROPS_MOM,
	MAX(LEN(PRICE_DROPS_YOY))PRICE_DROPS_YOY,
	MAX(LEN(OFF_MARKET_IN_TWO_WEEKS))OFF_MARKET_IN_TWO_WEEKS,
	MAX(LEN(OFF_MARKET_IN_TWO_WEEKS_MOM))OFF_MARKET_IN_TWO_WEEKS_MOM,
	MAX(LEN(OFF_MARKET_IN_TWO_WEEKS_YOY))OFF_MARKET_IN_TWO_WEEKS_YOY,
	MAX(LEN(PARENT_METRO_REGION))PARENT_METRO_REGION,
	MAX(LEN(PARENT_METRO_REGION_METRO_CODE))PARENT_METRO_REGION_METRO_CODE,
	MAX(LEN(LAST_UPDATED))LAST_UPDATED
	FROM [RealEstate].[dbo].[neighborhood_market_tracker]

	DROP table if exists dbo.[neighborhood_market_tracker_prod]
	CREATE TABLE dbo.[neighborhood_market_tracker_prod](
	PERIOD_BEGIN DATE,
	PERIOD_END DATE,
	PERIOD_DURATION INT,
	REGION_TYPE VARCHAR(50),
	REGION_TYPE_ID INT,
	TABLE_ID INT,
	IS_SEASONALLY_ADJUSTED BIT,
	REGION VARCHAR(100),
	CITY varchar(100),
	STATE varchar(20),
	STATE_CODE CHAR(2),
	PROPERTY_TYPE varchar(50),
	PROPERTY_TYPE_ID INT,
	MEDIAN_SALE_PRICE NUMERIC(18,4),
	MEDIAN_SALE_PRICE_MOM FLOAT,
	MEDIAN_SALE_PRICE_YOY FLOAT,
	MEDIAN_LIST_PRICE NUMERIC(18,4),
	MEDIAN_LIST_PRICE_MOM FLOAT,
	MEDIAN_LIST_PRICE_YOY FLOAT,
	MEDIAN_PPSF NUMERIC(18,4),
	MEDIAN_PPSF_MOM FLOAT,
	MEDIAN_PPSF_YOY FLOAT,
	MEDIAN_LIST_PPSF NUMERIC(18,4),
	MEDIAN_LIST_PPSF_MOM FLOAT,
	MEDIAN_LIST_PPSF_YOY FLOAT,
	HOMES_SOLD INT,
	HOMES_SOLD_MOM NUMERIC(18,4),
	HOMES_SOLD_YOY NUMERIC(18,4),
	PENDING_SALES INT,
	PENDING_SALES_MOM NUMERIC(18,4),
	PENDING_SALES_YOY NUMERIC(18,4),
	NEW_LISTINGS INT,
	NEW_LISTINGS_MOM NUMERIC(18,4),
	NEW_LISTINGS_YOY NUMERIC(18,4),
	INVENTORY INT,
	INVENTORY_MOM float,
	INVENTORY_YOY NUMERIC(18,4),
	MONTHS_OF_SUPPLY NUMERIC(18,4),
	MONTHS_OF_SUPPLY_MOM float,
	MONTHS_OF_SUPPLY_YOY NUMERIC(18,4),
	MEDIAN_DOM NUMERIC(18,4),
	MEDIAN_DOM_MOM float,
	MEDIAN_DOM_YOY NUMERIC(18,4),
	AVG_SALE_TO_LIST NUMERIC(18,4),
	AVG_SALE_TO_LIST_MOM float,
	AVG_SALE_TO_LIST_YOY FLOAT,
	SOLD_ABOVE_LIST NUMERIC(18,4),
	SOLD_ABOVE_LIST_MOM FLOAT,
	SOLD_ABOVE_LIST_YOY FLOAT,
	PRICE_DROPS NUMERIC(18,4),
	PRICE_DROPS_MOM float,
	PRICE_DROPS_YOY NUMERIC(18,4),
	OFF_MARKET_IN_TWO_WEEKS NUMERIC(18,4),
	OFF_MARKET_IN_TWO_WEEKS_MOM FLOAT,
	OFF_MARKET_IN_TWO_WEEKS_YOY FLOAT,
	PARENT_METRO_REGION VARCHAR(50),
	PARENT_METRO_REGION_METRO_CODE INT,
	LAST_UPDATED DATETIMEOFFSET,
	Id Int
	) ON [PRIMARY]

	/************************************************************************************************************************
		2.	Add Id column for easy row identification, update, delete operations
	************************************************************************************************************************/
	
	alter table [RealEstate].[dbo].[neighborhood_market_tracker]
	add  id int identity(1,1)

GO

	/************************************************************************************************************************
		3.	Try to insert data into table neighborhood_market_tracker_prod
	************************************************************************************************************************/
	
	truncate table [dbo].[neighborhood_market_tracker_prod]
	begin try
		insert into [dbo].[neighborhood_market_tracker_prod]
		SELECT
		CASE WHEN PERIOD_BEGIN='NA' THEN NULL ELSE PERIOD_BEGIN END PERIOD_BEGIN,
		CASE WHEN PERIOD_END='NA' THEN NULL ELSE PERIOD_END END PERIOD_END,
		CASE WHEN PERIOD_DURATION='NA' THEN NULL ELSE PERIOD_DURATION END PERIOD_DURATION,
		CASE WHEN REGION_TYPE='NA' THEN NULL ELSE REGION_TYPE END REGION_TYPE,
		CASE WHEN REGION_TYPE_ID='NA' THEN NULL ELSE REGION_TYPE_ID END REGION_TYPE_ID,
		CASE WHEN TABLE_ID='NA' THEN NULL ELSE TABLE_ID END TABLE_ID,
		CASE WHEN IS_SEASONALLY_ADJUSTED='NA' THEN NULL ELSE IS_SEASONALLY_ADJUSTED END IS_SEASONALLY_ADJUSTED,
		CASE WHEN REGION='NA' THEN NULL ELSE REGION END REGION,
		CASE WHEN CITY='NA' THEN NULL ELSE CITY END CITY,
		CASE WHEN STATE='NA' THEN NULL ELSE STATE END STATE,
		CASE WHEN STATE_CODE='NA' THEN NULL ELSE STATE_CODE END STATE_CODE,
		CASE WHEN PROPERTY_TYPE='NA' THEN NULL ELSE PROPERTY_TYPE END PROPERTY_TYPE,
		CASE WHEN PROPERTY_TYPE_ID='NA' THEN NULL ELSE PROPERTY_TYPE_ID END PROPERTY_TYPE_ID,
		CASE WHEN MEDIAN_SALE_PRICE='NA' THEN NULL ELSE MEDIAN_SALE_PRICE END MEDIAN_SALE_PRICE,
		CASE WHEN MEDIAN_SALE_PRICE_MOM='NA' THEN NULL ELSE MEDIAN_SALE_PRICE_MOM END MEDIAN_SALE_PRICE_MOM,
		CASE WHEN MEDIAN_SALE_PRICE_YOY='NA' THEN NULL ELSE MEDIAN_SALE_PRICE_YOY END MEDIAN_SALE_PRICE_YOY,
		CASE WHEN MEDIAN_LIST_PRICE='NA' THEN NULL ELSE MEDIAN_LIST_PRICE END MEDIAN_LIST_PRICE,
		CASE WHEN MEDIAN_LIST_PRICE_MOM='NA' THEN NULL ELSE MEDIAN_LIST_PRICE_MOM END MEDIAN_LIST_PRICE_MOM,
		CASE WHEN MEDIAN_LIST_PRICE_YOY='NA' THEN NULL ELSE MEDIAN_LIST_PRICE_YOY END MEDIAN_LIST_PRICE_YOY,
		CASE WHEN MEDIAN_PPSF='NA' THEN NULL ELSE MEDIAN_PPSF END MEDIAN_PPSF,
		CASE WHEN MEDIAN_PPSF_MOM='NA' THEN NULL ELSE MEDIAN_PPSF_MOM END MEDIAN_PPSF_MOM,
		CASE WHEN MEDIAN_PPSF_YOY='NA' THEN NULL ELSE MEDIAN_PPSF_YOY END MEDIAN_PPSF_YOY,
		CASE WHEN MEDIAN_LIST_PPSF='NA' THEN NULL ELSE MEDIAN_LIST_PPSF END MEDIAN_LIST_PPSF,
		CASE WHEN MEDIAN_LIST_PPSF_MOM='NA' THEN NULL ELSE MEDIAN_LIST_PPSF_MOM END MEDIAN_LIST_PPSF_MOM,
		CASE WHEN MEDIAN_LIST_PPSF_YOY='NA' THEN NULL ELSE MEDIAN_LIST_PPSF_YOY END MEDIAN_LIST_PPSF_YOY,
		CASE WHEN HOMES_SOLD='NA' THEN NULL ELSE HOMES_SOLD END HOMES_SOLD,
		CASE WHEN HOMES_SOLD_MOM='NA' THEN NULL ELSE HOMES_SOLD_MOM END HOMES_SOLD_MOM,
		CASE WHEN HOMES_SOLD_YOY='NA' THEN NULL ELSE HOMES_SOLD_YOY END HOMES_SOLD_YOY,
		CASE WHEN PENDING_SALES='NA' THEN NULL ELSE PENDING_SALES END PENDING_SALES,
		CASE WHEN PENDING_SALES_MOM='NA' THEN NULL ELSE PENDING_SALES_MOM END PENDING_SALES_MOM,
		CASE WHEN PENDING_SALES_YOY='NA' THEN NULL ELSE PENDING_SALES_YOY END PENDING_SALES_YOY,
		CASE WHEN NEW_LISTINGS='NA' THEN NULL ELSE NEW_LISTINGS END NEW_LISTINGS,
		CASE WHEN NEW_LISTINGS_MOM='NA' THEN NULL ELSE NEW_LISTINGS_MOM END NEW_LISTINGS_MOM,
		CASE WHEN NEW_LISTINGS_YOY='NA' THEN NULL ELSE NEW_LISTINGS_YOY END NEW_LISTINGS_YOY,
		CASE WHEN INVENTORY='NA' THEN NULL ELSE INVENTORY END INVENTORY,
		CASE WHEN INVENTORY_MOM='NA' THEN NULL ELSE INVENTORY_MOM END INVENTORY_MOM,
		CASE WHEN INVENTORY_YOY='NA' THEN NULL ELSE INVENTORY_YOY END INVENTORY_YOY,
		CASE WHEN MONTHS_OF_SUPPLY='NA' THEN NULL ELSE MONTHS_OF_SUPPLY END MONTHS_OF_SUPPLY,
		CASE WHEN MONTHS_OF_SUPPLY_MOM='NA' THEN NULL ELSE MONTHS_OF_SUPPLY_MOM END MONTHS_OF_SUPPLY_MOM,
		CASE WHEN MONTHS_OF_SUPPLY_YOY='NA' THEN NULL ELSE MONTHS_OF_SUPPLY_YOY END MONTHS_OF_SUPPLY_YOY,
		CASE WHEN MEDIAN_DOM='NA' THEN NULL ELSE MEDIAN_DOM END MEDIAN_DOM,
		CASE WHEN MEDIAN_DOM_MOM='NA' THEN NULL ELSE MEDIAN_DOM_MOM END MEDIAN_DOM_MOM,
		CASE WHEN MEDIAN_DOM_YOY='NA' THEN NULL ELSE MEDIAN_DOM_YOY END MEDIAN_DOM_YOY,
		CASE WHEN AVG_SALE_TO_LIST='NA' THEN NULL ELSE AVG_SALE_TO_LIST END AVG_SALE_TO_LIST,
		CASE WHEN AVG_SALE_TO_LIST_MOM='NA' THEN NULL ELSE AVG_SALE_TO_LIST_MOM END AVG_SALE_TO_LIST_MOM,
		CASE WHEN AVG_SALE_TO_LIST_YOY='NA' THEN NULL ELSE AVG_SALE_TO_LIST_YOY END AVG_SALE_TO_LIST_YOY,
		CASE WHEN SOLD_ABOVE_LIST='NA' THEN NULL ELSE SOLD_ABOVE_LIST END SOLD_ABOVE_LIST,
		CASE WHEN SOLD_ABOVE_LIST_MOM='NA' THEN NULL ELSE SOLD_ABOVE_LIST_MOM END SOLD_ABOVE_LIST_MOM,
		CASE WHEN SOLD_ABOVE_LIST_YOY='NA' THEN NULL ELSE SOLD_ABOVE_LIST_YOY END SOLD_ABOVE_LIST_YOY,
		CASE WHEN PRICE_DROPS='NA' THEN NULL ELSE PRICE_DROPS END PRICE_DROPS,
		CASE WHEN PRICE_DROPS_MOM='NA' THEN NULL ELSE PRICE_DROPS_MOM END PRICE_DROPS_MOM,
		CASE WHEN PRICE_DROPS_YOY='NA' THEN NULL ELSE PRICE_DROPS_YOY END PRICE_DROPS_YOY,
		CASE WHEN OFF_MARKET_IN_TWO_WEEKS='NA' THEN NULL ELSE OFF_MARKET_IN_TWO_WEEKS END OFF_MARKET_IN_TWO_WEEKS,
		CASE WHEN OFF_MARKET_IN_TWO_WEEKS_MOM='NA' THEN NULL ELSE OFF_MARKET_IN_TWO_WEEKS_MOM END OFF_MARKET_IN_TWO_WEEKS_MOM,
		CASE WHEN OFF_MARKET_IN_TWO_WEEKS_YOY='NA' THEN NULL ELSE OFF_MARKET_IN_TWO_WEEKS_YOY END OFF_MARKET_IN_TWO_WEEKS_YOY,
		CASE WHEN PARENT_METRO_REGION='NA' THEN NULL ELSE PARENT_METRO_REGION END PARENT_METRO_REGION,
		CASE WHEN PARENT_METRO_REGION_METRO_CODE='NA' THEN NULL ELSE PARENT_METRO_REGION_METRO_CODE END PARENT_METRO_REGION_METRO_CODE,
		CASE WHEN LAST_UPDATED='NA' THEN NULL ELSE LAST_UPDATED END LAST_UPDATED,
		Id
		FROM [RealEstate].[dbo].[neighborhood_market_tracker]
		ORDER BY id
		
	/************************************************************************************************************************
		4.	Catch any errors from the try and investigate, should any arise 
	************************************************************************************************************************/

	end try
	begin catch
		select
        ERROR_NUMBER() AS ErrorNumber,
        ERROR_SEVERITY() AS ErrorSeverity,
        ERROR_STATE() AS ErrorState,
        ERROR_LINE() AS ErrorLine,
        ERROR_MESSAGE() AS ErrorMessage;
	end catch
	select @@IDENTITY

	